### ISSUE TITLE
Link to the dataset is broken.

### ISSUE THREAD

**Issue by XuyangBai** [hkust-vgd/lcd#1]
Hi, Thanks a lot for your sharing. Could you check the link to the dataset? I want  to take a look at the dataset but find the link is broken.

**Comment by pqhieu** [comment]
Hi, thanks for your interest. Have you tried to access using different networks or computers? I can still access the link normally.

**Comment by XuyangBai** [comment]
I tried to access under another networks and it is OK. Thanks !
