### ISSUE TITLE
Code to prepare own dataset

### ISSUE THREAD

**Issue by moguz** [hkust-vgd/lcd#3]
I would like to apply your method to another dataset, however it's not very clear to me the exact steps needed to prepare the 2D-3D corresponding data. When do you plan to provide resources for this? Could you share the code/ a detailed guideline?

**Comment by pqhieu** [comment]
Thanks for your interest. Unfortunately due to COVID, I don't have access to my code at the moment. I will release the code as soon as I can after I get my access. If you have any other questions, please send me an email or continue in this thread.

**Comment by pqhieu** [comment]
Sorry for the delay. I just updated the repo to include the script for 2D-3D extraction. Please take a look.
