### ISSUE TITLE
Experimental setup for training

### ISSUE THREAD

**Issue by gessfred** [hkust-vgd/lcd#4]
Hi,

I wish to re-train your network (later on a different dataset of my own) and I am trying to assess the resources needed. In the paper it is mentioned that on a cluster it took 17 hours. 

Could you please provide more details about your setup? Notably how many GPUs and what topology yielded this performance? Also, how to modify the training script to run on multiple GPUs - does `nn.DataParallel` suffice?

Thank you.

**Comment by pqhieu** [comment]
Hi,

We only used 1 GPU previously, so I cannot really help you on the multi GPU training. For the cluster, we had to request 100GB memory to load the entire dataset instead of caching as the current code. I will try to upload the version that loads the entire dataset onto memory soon. The configs that we used is the same as the release version.

Hope this helps.

**Comment by gessfred** [comment]
Thanks, that makes a lot of sense, the _IO_ seemed indeed to be the bottleneck on my side.

**Comment by gessfred** [comment]
Sorry, allow me a quick follow up. I have modified the Dataset naively and got a huge improvement, but I still project the training to last 80h on a V100, can you maybe spot an obvious inefficiency:

```python
class Match3DDataset(data.Dataset):
    def __init__(self, root):
        flist = sorted(glob.glob(os.path.join(root, '*.h5')))
        self.points, self.images = [], []
        for fname in flist:
            pts, ims = self.load(fname)
            self.points += list(pts)
            self.images += list(ims)
​
    def load(self, fname):
        f = h5py.File(fname, 'r')
        return f['points'][:], f['images'][:]
​
    def __getitem__(self, i):
        return self.points[i], self.images[i]        
​
    def __len__(self):
        return len(self.points)
```

Thanks.

**Comment by pqhieu** [comment]
FYI, I have added the original data loader implementation.
